global:
  scrape_interval: 30s
  scrape_timeout: 15s
  evaluation_interval: 10m

scrape_configs:
  - job_name: collect
    metrics_path: /metrics
    honor_timestamps: true
    scheme: http
    authorization:
      type: Bearer
      credentials: prometheus
    static_configs:
      - targets: ['localhost:8000']
